[package]
name = "hdl_sv"
version = "1.7.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.5.6", features = ["derive"] }
humansize = "1.1.1" 
rust-embed = "6"
threadpool = "1.8.1"
glob = "0.3.2"
log = "0.4"
env_logger = "0.11"